#!/usr/bin/python3
#

#  Copyright (C) 2015  Rafael Senties Martinelli 
#
#  This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License 3 as published by
#   the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA.

"""
    Trying to improve the "remove tests" feature, where the existante of a word in 
    a list must be checked.
"""


import re

combs=['thisprorksgram', 'thiswøprorks', 'thiswøgram', 'thiswøpro', 'thisprogramwø', 'thisgramwøpro', 'thisrksgram', 'thisprogram', 'thisrksprogram', 'thisprogramrks', 'thisrksgramwø', 'thisprorks', 'thisrksprowø', 'thiswøprogram', 'thisrkswø', 'thiswørks', 'thisgramprowø', 'thisgramrks', 'thisprowø', 'thisgrampro', 'thisrksgrampro', 'thisrkswøpro', 'thiswøgramrks', 'thiswørkspro', 'thisgramrkspro', 'thisrkspro', 'thisgramwørks', 'thisgramwø', 'thisgramprorks', 'thisgramrkswø', 'thisprowørks', 'thisrkswøgram', 'thisprorkswø', 'thisprowøgram', 'thiswørksgram', 'thiswøgrampro']

print("Normal Test:")
if 'thisprogramwørks' in combs:
    print(True)
else:
    print(False)

print()

print("Regex Test:")
compiled_strings=re.compile("|".join(map(re.escape, combs)))
if compiled_strings.match('thisprogramwørks'):
    print(True)
else:
    print(False)
